Repository RAF-SI-2023/Banka-2-Frontend, pull requests merged in 2024-07, with the labels that each got.

#224 Popravljene sitnice za interbank
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.css
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.html
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.css
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
Labels: size/M, lgtm, approved

#225 vracen view za dialog banke 3
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.html
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.ts
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.ts
Labels: size/M, lgtm, approved

#226 Hotfix za contract dugmad
  src/app/components/contracts/contract-info-dialog/contract-info-dialog.component.ts
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.ts
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
Labels: size/L, lgtm, approved

#227 Cypress Stock and OTC Tests
  README.md
  cypress/e2e/otc/interbank-otc.cy.ts
  cypress/e2e/otc/otc.cy.ts
  cypress/e2e/stock/stock-purchase.cy.ts
  cypress/e2e/stock/stock-sell.cy.ts
  cypress/support/commands.ts
  cypress/support/constants.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/acquired-securities/acquired-securities.component.html
  src/app/components/contracts/contract-info-dialog/contract-info-dialog.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.html
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html
  src/app/components/orders/order-info-dialog/order-info-dialog.component.html
  src/app/components/orders/orders.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-security-info-dialog/publicly-tradable-security-info-dialog.component.html
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.html
Labels: size/L, lgtm, approved

#228 margine transaction
  src/app/app.module.ts
  src/app/components/orders/create-margin-transaction/create-margin-transaction.component.css
  src/app/components/orders/create-margin-transaction/create-margin-transaction.component.html
  src/app/components/orders/create-margin-transaction/create-margin-transaction.component.spec.ts
  src/app/components/orders/create-margin-transaction/create-margin-transaction.component.ts
  src/app/components/orders/order-info-dialog/order-info-dialog.component.html
  src/app/components/orders/order-info-dialog/order-info-dialog.component.ts
  src/app/dtos/margin-transaction-send-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/margin-transaction.service.spec.ts
  src/app/services/bank-service/margin-transaction.service.ts
  src/environments/environment.development.ts
Labels: size/L, lgtm, approved

#230 Update README.md
  README.md
Labels: size/XS, lgtm, approved

#232 Post-final build
  README.md
  cypress.config.ts
  package-lock.json
  src/app/app.module.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
  src/app/dtos/margin-transaction-send-dto.ts
  src/app/services/bank-service/margin-transaction.service.ts
Labels: size/M, lgtm, approved
