Repository RAF-SI-2023/Banka-2-Frontend, pull requests merged in 2024-06, with the labels that each got.

#172 Update build.yaml
  .prow/build.yaml
Labels: size/XS, approved

#175 dodat block u dto i u cards
  .prow/frontend.yaml
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/cards/cards.component.html
  src/app/components/cards/change-block-form/card-block-status-dialog/card-block-status-dialog.component.css
  src/app/components/cards/change-block-form/card-block-status-dialog/card-block-status-dialog.component.html
  src/app/components/cards/change-block-form/card-block-status-dialog/card-block-status-dialog.component.spec.ts
  src/app/components/cards/change-block-form/card-block-status-dialog/card-block-status-dialog.component.ts
  src/app/components/cards/change-block-form/change-block-form.component.css
  src/app/components/cards/change-block-form/change-block-form.component.html
  src/app/components/cards/change-block-form/change-block-form.component.spec.ts
  src/app/components/cards/change-block-form/change-block-form.component.ts
  src/app/components/create-bank-profile/create-bank-profile.component.html
  src/app/components/user-profile/cards-info-dialog/cards-info-dialog.component.html
  src/app/components/user-profile/cards-info-dialog/cards-info-dialog.component.ts
  src/app/dtos/card-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/card.service.ts
  src/app/utils/constants/dropdown.constants.ts
  src/environments/environment.development.ts
Labels: size/L, lgtm, approved

#178 Popravljen prod
  angular.json
  src/app/components/bank-profits/bank-profits.component.ts
  src/app/components/cards/change-block-form/change-block-form.component.ts
  src/app/components/options/option-info-dialog/option-info-dialog.component.ts
  src/app/services/bank-service/account.service.ts
  src/app/services/bank-service/action-agent-profit.service.ts
  src/app/services/bank-service/bank-exchange.service.ts
  src/app/services/bank-service/bank-profit.service.ts
  src/app/services/bank-service/bank-transfer-transaction-details.service.ts
  src/app/services/bank-service/card.service.ts
  src/app/services/bank-service/credit.service.ts
  src/app/services/bank-service/order-transaction.service.ts
  src/app/services/bank-service/order.service.ts
  src/app/services/bank-service/securities.service.ts
  src/app/services/bank-service/transaction.service.ts
  src/app/services/iam-service/auth.service.ts
  src/app/services/iam-service/company.service.ts
  src/app/services/iam-service/user.service.ts
  src/app/services/otc-service/contract.service.ts
  src/app/services/stock-service/currency.service.ts
  src/app/services/stock-service/exchange.service.ts
  src/app/services/stock-service/forex.service.ts
  src/app/services/stock-service/futures-contract.service.ts
  src/app/services/stock-service/option.service.ts
  src/app/services/stock-service/stock.service.ts
Labels: size/L, lgtm, approved

#180 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#181 getApproved i getRejected Contracts
  .prow/build.yaml
  src/app/components/actuaries/actuaries.component.html
  src/app/components/bank-exchange/bank-exchange.component.html
  src/app/components/bank-profits/agent-profits/agent-profits.component.css
  src/app/components/bank-profits/agent-profits/agent-profits.component.html
  src/app/components/bank-profits/bank-transactions-profits/bank-transactions-profits.component.css
  src/app/components/bank-profits/bank-transactions-profits/bank-transactions-profits.component.html
  src/app/components/companies/all-company-employees/all-company-employees.component.html
  src/app/components/companies/companies.component.html
  src/app/components/contracts/contracts.component.ts
  src/app/components/credit-requests/credit-requests.component.html
  src/app/components/forex/forex.component.html
  src/app/components/futures-contracts/futures-contracts.component.html
  src/app/components/money-transactions-all/money-transactions-all.component.css
  src/app/components/money-transactions-all/money-transactions-all.component.html
  src/app/components/order-transactions-all/order-transactions-all.component.css
  src/app/components/order-transactions-all/order-transactions-all.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.html
  src/app/components/stocks/stocks.component.html
  src/app/components/users/users.component.html
  src/app/services/api-routes.ts
  src/app/services/otc-service/contract.service.ts
Labels: size/M, lgtm, approved

#183 Prod/dev update
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#187 Prod/dev update
  .prow/build.yaml
  Dockerfile
  package.json
  src/app/components/actuaries/actuaries.component.html
  src/app/components/bank-exchange/bank-exchange.component.html
  src/app/components/bank-profits/agent-profits/agent-profits.component.css
  src/app/components/bank-profits/agent-profits/agent-profits.component.html
  src/app/components/bank-profits/bank-transactions-profits/bank-transactions-profits.component.css
  src/app/components/bank-profits/bank-transactions-profits/bank-transactions-profits.component.html
  src/app/components/companies/all-company-employees/all-company-employees.component.html
  src/app/components/companies/companies.component.html
  src/app/components/contracts/contracts.component.ts
  src/app/components/credit-requests/credit-requests.component.html
  src/app/components/forex/forex.component.html
  src/app/components/futures-contracts/futures-contracts.component.html
  src/app/components/money-transactions-all/money-transactions-all.component.css
  src/app/components/money-transactions-all/money-transactions-all.component.html
  src/app/components/order-transactions-all/order-transactions-all.component.css
  src/app/components/order-transactions-all/order-transactions-all.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.html
  src/app/components/stocks/stocks.component.html
  src/app/components/users/users.component.html
  src/app/services/api-routes.ts
  src/app/services/otc-service/contract.service.ts
Labels: size/L, lgtm, approved

#188 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#190 Update build.yaml
  .prow/build.yaml
  angular.json
Labels: lgtm, approved

#193 Update build.yaml
  .prow/build.yaml
Labels: size/M, lgtm, approved

#196 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#195 Helm update
  .prow/build.yaml
  angular.json
Labels: size/M, lgtm, approved

#197 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#198 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#199 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#200 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#202 Update README.md
  README.md
Labels: lgtm, approved

#205 Popravka build.yaml i dodatak Cypress testovi
  .prow/build.yaml
  cypress/e2e/exchange/exchange.cy.ts
  cypress/e2e/exchange/internal-exchange.cy.ts
  src/app/components/bank-exchange/bank-exchange.component.html
  src/app/components/money-transactions/internal-form/internal-form.component.html
  src/app/services/api-routes.ts
Labels: size/M, lgtm, approved

#208 Popravljene sitnice
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/acquired-securities/acquired-securities.component.ts
  src/app/components/companies/companies.component.html
  src/app/components/companies/companies.component.ts
  src/app/components/contracts/contract-info-dialog/contract-info-dialog.component.html
  src/app/components/contracts/contracts.component.html
  src/app/components/contracts/contracts.component.ts
  src/app/components/home/home.component.html
  src/app/components/margin-accounts/dialogs/add-margin-account-dialog/add-margin-account-dialog.component.html
  src/app/components/margin-accounts/dialogs/add-margin-account-dialog/add-margin-account-dialog.component.spec.ts
  src/app/components/margin-accounts/dialogs/add-margin-account-dialog/add-margin-account-dialog.component.ts
  src/app/components/margin-accounts/dialogs/edit-margin-account-dialog/edit-margin-account-dialog.component.spec.ts
  src/app/components/margin-accounts/dialogs/edit-margin-account-dialog/edit-margin-account-dialog.component.ts
  src/app/components/margin-accounts/dialogs/margin-account-info-dialog/margin-account-info-dialog.component.html
  src/app/components/margin-accounts/dialogs/margin-account-info-dialog/margin-account-info-dialog.component.spec.ts
  src/app/components/margin-accounts/dialogs/margin-account-info-dialog/margin-account-info-dialog.component.ts
  src/app/components/margin-accounts/margin-accounts.component.html
  src/app/components/margin-accounts/margin-accounts.component.spec.ts
  src/app/components/margin-accounts/margin-accounts.component.ts
  src/app/components/payments/payments.component.spec.ts
  src/app/components/payments/payments.component.ts
  src/app/components/user-profile/user-profile.component.css
  src/app/components/user-profile/user-profile.component.html
  src/app/components/user-profile/user-profile.component.ts
  src/app/dtos/margin-account-dto.ts
  src/app/dtos/margin-transaction-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/margin-accounts.service.spec.ts
  src/app/services/bank-service/margin-accounts.service.ts
Labels: size/XL, lgtm, approved

#209 Popravljene sitnice
  cypress.config.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/home/home.component.html
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/user-profile/user-profile.component.css
  src/app/components/user-profile/user-profile.component.html
Labels: size/S, lgtm, approved

#212 Hotfix
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#214 dodata mogucnost -1 za forex,options,akcije,
  src/app/components/contracts/contract-info-dialog/contract-info-dialog.component.ts
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.ts
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.ts
  src/app/components/options/option-info-dialog/option-info-dialog.component.ts
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts
Labels: size/M, lgtm, approved

#216 Napravljena komponenta i servis interbank-tradable-securities
  src/app/app.module.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.css
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.spec.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
  src/app/dtos/bank-otc-stock-dto.ts
  src/app/services/api-routes.ts
  src/app/services/otc-service/interbank-tradable-securities.service.spec.ts
  src/app/services/otc-service/interbank-tradable-securities.service.ts
Labels: size/L, lgtm, approved

#218 Popravljene komponente vezane za OTC izmedju banaka
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.ts
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.css
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.spec.ts
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.css
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
  src/app/components/otc-offers/otc-offers.component.spec.ts
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts
  src/app/components/user-profile/cards-info-dialog/cards-info-dialog.component.ts
  src/app/dtos/offer-dto.ts
  src/app/services/api-routes.ts
  src/app/services/otc-service/bank-otc.service.spec.ts
  src/app/services/otc-service/bank-otc.service.ts
  src/app/services/otc-service/interbank-tradable-securities.service.spec.ts
  src/app/utils/constants/translate.constants.ts
  src/environments/environment.development.ts
Labels: size/L, lgtm, approved

#219 Ubacene interbank rute u navbar
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/navigation-menu/navigation-menu.component.ts
  src/app/dtos/frontend-offer-dto.ts
  src/app/services/otc-service/bank-otc.service.ts
Labels: size/L, lgtm, approved

#220 Dodat hint, pre-test Cypress
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.css
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.html
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.css
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.html
  src/app/components/options/option-info-dialog/option-info-dialog.component.css
  src/app/components/options/option-info-dialog/option-info-dialog.component.html
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.css
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.html
Labels: size/M, lgtm, approved

#221 refresh btn, view dialog 2x,
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.css
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.html
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.spec.ts
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.ts
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.css
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.css
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.html
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.spec.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.css
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
Labels: size/XL, lgtm, approved

#222 dodato delete dugme i povezano sa backom za interbank-securities-offe…
  src/app/app.module.ts
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.css
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.html
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.spec.ts
  src/app/components/interbank-securities-offers/dialogs/view-interbank-offer-dialog/view-interbank-offer-dialog.component.ts
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.css
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.html
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.spec.ts
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.ts
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.css
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.html
  src/app/components/interbank-tradable-securities/interbank-tradable-securities.component.ts
Labels: size/XL, lgtm, approved

#223 izmena povezan service
  src/app/components/interbank-securities-offers/interbank-securities-offers.component.html
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.html
  src/app/components/interbank-tradable-securities/dialogs/new-interbank-offer-dialog/new-interbank-offer-dialog.component.ts
Labels: size/S, lgtm, approved
