Repository RAF-SI-2023/Banka-2-Frontend, pull requests merged in 2024-05, with the labels that each got.

#138 4 More Cypress Tests
  README.md
  cypress/e2e/agent/add-agent.cy.ts
  cypress/e2e/company/add-company.cy.ts
  cypress/e2e/company/delete-company.cy.ts
  cypress/e2e/credits/create-credit-request.cy.ts
  cypress/e2e/users/add-employee.cy.ts
  cypress/e2e/users/delete-user.cy.ts
  src/app/components/actuaries/add-agent-dialog/add-agent-dialog.component.html
  src/app/components/companies/companies.component.html
  src/app/components/companies/dialogs/add-company-dialog/add-company-dialog.component.html
  src/app/components/create-credit-request/create-credit-request.component.html
Labels: size/L, lgtm, approved

#145 Acquired Securities Requests
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.css
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.html
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.ts
  src/app/components/acquired-securities/requests/requests.component.css
  src/app/components/acquired-securities/requests/requests.component.html
  src/app/components/acquired-securities/requests/requests.component.spec.ts
  src/app/components/acquired-securities/requests/requests.component.ts
  src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.ts
  src/app/services/api-routes.ts
  src/app/services/iam-service/user.service.ts
Labels: size/XL, lgtm, approved

#151 sigurnosti privatne i javne
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.css
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.spec.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.ts
  src/app/components/acquired-securities/acquired-securities.component.css
  src/app/components/acquired-securities/acquired-securities.component.html
  src/app/components/acquired-securities/acquired-securities.component.spec.ts
  src/app/components/acquired-securities/acquired-securities.component.ts
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.css
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.spec.ts
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.css
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.spec.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.ts
  src/app/dtos/security-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/securities.service.spec.ts
  src/app/services/bank-service/securities.service.ts
Labels: size/XL, lgtm, approved

#152 Izmenjene forme za public/acquired securities
  .prow/frontend.yaml
  README.md
  cypress/e2e/agent/add-agent.cy.ts
  cypress/e2e/credits/create-credit-request.cy.ts
  cypress/e2e/users/add-employee.cy.ts
  src/app/app.module.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.css
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.spec.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.ts
  src/app/components/acquired-securities/acquired-securities.component.html
  src/app/components/acquired-securities/acquired-securities.component.spec.ts
  src/app/components/acquired-securities/acquired-securities.component.ts
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.css
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.ts
  src/app/components/acquired-securities/requests/requests.component.css
  src/app/components/acquired-securities/requests/requests.component.spec.ts
  src/app/components/acquired-securities/requests/requests.component.ts
  src/app/components/create-credit-request/create-credit-request.component.html
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.css
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.spec.ts
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.spec.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.ts
  src/app/components/transactions-all/transactions-all.component.ts
  src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.ts
  src/app/dtos/security-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/securities.service.spec.ts
  src/app/services/bank-service/securities.service.ts
  src/app/services/bank-service/transaction.service.ts
  src/app/services/iam-service/user.service.ts
Labels: size/XXL, lgtm, approved

#153 Navbar link toggle group
  README.md
  src/app/components/navigation-menu/navigation-menu.component.css
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/navigation-menu/navigation-menu.component.ts
Labels: size/M, lgtm, approved

#155 opcije info dialog i popravka javnih sigurnosti
  src/app/app.module.ts
  src/app/components/options/option-info-dialog/option-info-dialog.component.css
  src/app/components/options/option-info-dialog/option-info-dialog.component.html
  src/app/components/options/option-info-dialog/option-info-dialog.component.spec.ts
  src/app/components/options/option-info-dialog/option-info-dialog.component.ts
  src/app/components/options/options.component.html
  src/app/components/options/options.component.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/securities.service.ts
  src/app/services/iam-service/user.service.ts
Labels: size/XL, lgtm, approved

#156 Dodati kontroleri za nove funkcionalnosti, popravljene neke stvari
  .prettierrc
  src/app/app.module.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.ts
  src/app/components/acquired-securities/acquired-securities.component.html
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.html
  src/app/components/companies/dialogs/company-info-dialog/company-info-dialog.component.html
  src/app/components/credit-requests/credit-req-info-dialog/credit-req-info-dialog.component.html
  src/app/components/credits/dialogs/credit-info-dialog/credit-info-dialog.component.html
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.html
  src/app/components/currency-exchange/dialogs/exchange-info-dialog/exchange-info-dialog.component.html
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.html
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.html
  src/app/components/options/option-info-dialog/option-info-dialog.component.html
  src/app/components/options/option-info-dialog/option-info-dialog.component.spec.ts
  src/app/components/options/option-info-dialog/option-info-dialog.component.ts
  src/app/components/options/options.component.css
  src/app/components/options/options.component.html
  src/app/components/options/options.component.ts
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.ts
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.css
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.html
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts
  src/app/components/transactions-all/dialogs/transactions-all-info-dialog/transactions-all-info-dialog.component.html
  src/app/components/transactions-all/dialogs/transactions-all-info-dialog/transactions-all-info-dialog.component.spec.ts
  src/app/components/transactions-all/transactions-all.component.spec.ts
  src/app/dtos/contract-dto.ts
  src/app/dtos/order-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/account.service.ts
  src/app/services/bank-service/credit.service.ts
  src/app/services/bank-service/order.service.spec.ts
  src/app/services/bank-service/order.service.ts
  src/app/services/bank-service/securities.service.ts
  src/app/services/bank-service/transaction.service.ts
  src/app/services/otc-service/contract.service.spec.ts
  src/app/services/otc-service/contract.service.ts
  src/app/services/stock-service/exchange.service.ts
  src/app/services/stock-service/futures-contract.service.ts
  src/app/services/stock-service/stock.service.ts
  src/environments/environment.development.ts
  src/environments/environment.ts
Labels: size/XXL, lgtm, approved

#157 createContract nad podacima napravljen
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.css
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.html
  src/app/components/forex/forex-info-dialog/forex-info-dialog.component.ts
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.css
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.html
  src/app/components/futures-contracts/futures-contract-info-dialog/futures-contract-info-dialog.component.ts
  src/app/components/options/option-info-dialog/option-info-dialog.component.css
  src/app/components/options/option-info-dialog/option-info-dialog.component.html
  src/app/components/options/option-info-dialog/option-info-dialog.component.ts
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.ts
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.css
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.html
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts
Labels: size/L, lgtm, approved

#158 fix za acquired-securities dialog close
  src/app/components/acquired-securities/acquired-securities.component.ts
  src/app/components/home/home.component.ts
Labels: size/S, lgtm, approved

#159 Orders Page with Filters
  README.md
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/orders/info-dialog/info-dialog.component.css
  src/app/components/orders/info-dialog/info-dialog.component.html
  src/app/components/orders/info-dialog/info-dialog.component.spec.ts
  src/app/components/orders/info-dialog/info-dialog.component.ts
  src/app/components/orders/orders.component.css
  src/app/components/orders/orders.component.html
  src/app/components/orders/orders.component.spec.ts
  src/app/components/orders/orders.component.ts
  src/app/dtos/order-dto.ts
Labels: size/XL, lgtm, approved

#161 build.yaml
  .prow/build.yaml
  .prow/frontend.yaml
  README.md
  cypress.config.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/acquired-securities/acquired-securities.component.ts
  src/app/components/acquired-securities/requests/request-info-dialog/request-info-dialog.component.ts
  src/app/components/actuaries/actuary-info-dialog/actuary-info-dialog.component.ts
  src/app/components/companies/dialogs/company-info-dialog/company-info-dialog.component.ts
  src/app/components/credit-requests/credit-req-info-dialog/credit-req-info-dialog.component.ts
  src/app/components/credits/dialogs/credit-info-dialog/credit-info-dialog.component.ts
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.ts
  src/app/components/currency-exchange/dialogs/exchange-info-dialog/exchange-info-dialog.component.ts
  src/app/components/orders/info-dialog/info-dialog.component.spec.ts
  src/app/components/orders/info-dialog/info-dialog.component.ts
  src/app/components/orders/order-info-dialog/order-info-dialog.component.css
  src/app/components/orders/order-info-dialog/order-info-dialog.component.html
  src/app/components/orders/order-info-dialog/order-info-dialog.component.spec.ts
  src/app/components/orders/order-info-dialog/order-info-dialog.component.ts
  src/app/components/orders/orders.component.css
  src/app/components/orders/orders.component.html
  src/app/components/orders/orders.component.spec.ts
  src/app/components/orders/orders.component.ts
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.html
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts
  src/app/components/transactions-all/dialogs/transactions-all-info-dialog/transaction-all-info-dialog.component.ts
  src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.ts
  src/app/dtos/account-dto.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/account.service.ts
  src/app/services/bank-service/card.service.ts
  src/app/services/bank-service/credit.service.ts
  src/app/services/bank-service/order.service.ts
  src/app/services/bank-service/securities.service.ts
  src/app/services/iam-service/company.service.ts
  src/app/services/iam-service/user.service.ts
  src/app/services/stock-service/futures-contract.service.ts
Labels: size/XL, lgtm, approved

#162 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#163 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#167 Ispravljeni testovi
  .prow/frontend.yaml
  Dockerfile
  cypress.config.ts
  cypress/e2e/company/add-company.cy.ts
  cypress/e2e/company/delete-company.cy.ts
  cypress/e2e/credits/create-credit-request.cy.ts
  cypress/e2e/login.cy.ts
  cypress/e2e/router.cy.ts
  cypress/e2e/users/add-agent.cy.ts
  cypress/e2e/users/add-employee.cy.ts
  cypress/e2e/users/delete-agent.cy.ts
  cypress/e2e/users/delete-employee.cy.ts
  cypress/e2e/users/delete-user.cy.ts
  cypress/e2e/users/password-change.cy.ts
  cypress/screenshots/delete-button.png
  cypress/support/constants.ts
  docker-compose.yml
  package-lock.json
  package.json
  src/app/app.component.css
  src/environments/environment.development.ts
Labels: size/L, lgtm, approved

#168 Popravka DTO request-a
  cypress/e2e/users/delete-agent.cy.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.ts
  src/app/components/acquired-securities/acquired-securities.component.html
  src/app/components/acquired-securities/acquired-securities.component.ts
  src/app/components/contracts/contracts.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.ts
  src/app/components/stocks/stocks.component.html
  src/app/components/stocks/stocks.component.ts
  src/app/dtos/security-dto.ts
  src/app/services/iam-service/user.service.ts
Labels: size/L, lgtm, approved

#171 SecurityDto fix
  cypress/e2e/users/delete-agent.cy.ts
  cypress/e2e/users/delete-employee.cy.ts
  src/app/app.module.ts
  src/app/components/acquired-securities/acquired-securities-info-dialog/acquired-securities-info-dialog.component.html
  src/app/components/publicly-tradable-securities/public-security-info-dialog/public-security-info-dialog.component.spec.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-securities.component.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-security-info-dialog/publicly-tradable-security-info-dialog.component.css
  src/app/components/publicly-tradable-securities/publicly-tradable-security-info-dialog/publicly-tradable-security-info-dialog.component.html
  src/app/components/publicly-tradable-securities/publicly-tradable-security-info-dialog/publicly-tradable-security-info-dialog.component.spec.ts
  src/app/components/publicly-tradable-securities/publicly-tradable-security-info-dialog/publicly-tradable-security-info-dialog.component.ts
Labels: size/L, lgtm, approved
