Repository RAF-SI-2023/Banka-2-Frontend, pull requests merged in 2024-04, with the labels that each got.

#92 feat/forex
  src/app/components/forex/forex.component.css
  src/app/components/forex/forex.component.html
  src/app/components/forex/forex.component.ts
  src/app/dtos/forex-dto.ts
  src/app/services/api-routes.ts
  src/app/services/stock.service.ts
  src/environments/environment.ts
Labels: size/L

#104 change-password style and validation
  src/app/components/password-change/password-change.component.css
  src/app/components/password-change/password-change.component.html
  src/app/components/password-change/password-change.component.ts
Labels: size/L

#103 zakomentarisan deo za menjanje para
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/currency-exchange/currency-exchange.component.css
  src/app/components/currency-exchange/currency-exchange.component.html
  src/app/components/currency-exchange/currency-exchange.component.ts
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.css
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.html
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.spec.ts
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.ts
  src/app/components/currency-exchange/dialogs/exchange-info-dialog/exchange-info-dialog.component.css
  src/app/components/currency-exchange/dialogs/exchange-info-dialog/exchange-info-dialog.component.html
  src/app/components/currency-exchange/dialogs/exchange-info-dialog/exchange-info-dialog.component.spec.ts
  src/app/components/currency-exchange/dialogs/exchange-info-dialog/exchange-info-dialog.component.ts
Labels: size/L

#105 Update in user table
  src/app/components/users/dialogs/update-user-dialog/update-user-dialog.component.html
  src/app/components/users/dialogs/update-user-dialog/update-user-dialog.component.ts
  src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.html
  src/app/components/users/dialogs/user-info-dialog/user-info-dialog.component.ts
Labels: size/S

#108 fix za mapiranje curreny info
  src/app/app-routing.module.ts
  src/app/components/currency-exchange/dialogs/currency-info-dialog/currency-info-dialog.component.ts
  src/app/components/options/options.component.css
  src/app/components/options/options.component.html
  src/app/components/options/options.component.ts
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.html
  src/app/components/stocks/dialogs/stock-info-dialog/stock-info-dialog.component.ts
  src/app/components/stocks/stocks.component.ts
  src/app/dtos/options-dto.ts
  src/app/services/api-routes.ts
  src/app/services/stock.service.ts
Labels: size/L

#115 Credits and Create Credit Request
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/create-credit-request/create-credit-request.component.css
  src/app/components/create-credit-request/create-credit-request.component.html
  src/app/components/create-credit-request/create-credit-request.component.spec.ts
  src/app/components/create-credit-request/create-credit-request.component.ts
  src/app/components/credits/credits.component.css
  src/app/components/credits/credits.component.html
  src/app/components/credits/credits.component.spec.ts
  src/app/components/credits/credits.component.ts
  src/app/components/credits/dialogs/credit-info-dialog/credit-info-dialog.component.css
  src/app/components/credits/dialogs/credit-info-dialog/credit-info-dialog.component.html
  src/app/components/credits/dialogs/credit-info-dialog/credit-info-dialog.component.spec.ts
  src/app/components/credits/dialogs/credit-info-dialog/credit-info-dialog.component.ts
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/dtos/account-dto.ts
  src/app/dtos/create-credit-request-dto.ts
  src/app/dtos/credit-dto.ts
  src/app/pipes/translate.pipe.spec.ts
  src/app/pipes/translate.pipe.ts
  src/app/services/api-routes.ts
  src/app/services/auth.service.ts
  src/app/services/bank.service.ts
  src/app/services/credit.service.spec.ts
  src/app/services/credit.service.ts
  src/app/utils/constants/dropdown.constants.ts
  src/app/utils/constants/index.ts
  src/app/utils/constants/translate.constants.ts
  src/app/utils/validators/bank-account-number-no-symbols.validator.ts
Labels: size/XXL

#119 Basic Stock Filter Options
  src/app/app.module.ts
  src/app/components/stocks/dialogs/stock-filter/stock-filter.component.css
  src/app/components/stocks/dialogs/stock-filter/stock-filter.component.html
  src/app/components/stocks/dialogs/stock-filter/stock-filter.component.spec.ts
  src/app/components/stocks/dialogs/stock-filter/stock-filter.component.ts
  src/app/components/stocks/stocks.component.html
  src/app/components/stocks/stocks.component.ts
  src/environments/environment.development.ts
Labels: size/L

#118 transaction page/service
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/transactions/external-form/external-form.component.css
  src/app/components/transactions/external-form/external-form.component.html
  src/app/components/transactions/external-form/external-form.component.spec.ts
  src/app/components/transactions/external-form/external-form.component.ts
  src/app/components/transactions/internal-form/internal-form.component.css
  src/app/components/transactions/internal-form/internal-form.component.html
  src/app/components/transactions/internal-form/internal-form.component.spec.ts
  src/app/components/transactions/internal-form/internal-form.component.ts
  src/app/components/transactions/transactions/transactions.component.css
  src/app/components/transactions/transactions/transactions.component.html
  src/app/components/transactions/transactions/transactions.component.spec.ts
  src/app/components/transactions/transactions/transactions.component.ts
  src/app/dtos/external-transaction-response-dto.ts
  src/app/dtos/internal-transaction-response-dto.ts
  src/app/dtos/simple-transaction-dto.ts
  src/app/dtos/transaction-dto.ts
  src/app/pipes/account-number-format.pipe.spec.ts
  src/app/pipes/account-number-format.pipe.ts
  src/app/services/api-routes.ts
  src/app/services/bank-service/transaction.service.spec.ts
  src/app/services/bank-service/transaction.service.ts
  src/app/utils/constants/dropdown.constants.ts
  src/environments/environment.ts
Labels: size/XL

#120 fix za companies select i izmena za user select
  src/app/components/companies/companies.component.html
  src/app/components/companies/companies.component.ts
  src/app/components/users/users.component.ts
  src/environments/environment.development.ts
Labels: size/M

#122 external transaction i conferm dialog za njega
  src/app/app.module.ts
  src/app/components/transactions/confirm-dialog/confirm-dialog.component.css
  src/app/components/transactions/confirm-dialog/confirm-dialog.component.html
  src/app/components/transactions/confirm-dialog/confirm-dialog.component.spec.ts
  src/app/components/transactions/confirm-dialog/confirm-dialog.component.ts
  src/app/components/transactions/external-form/external-form.component.html
  src/app/components/transactions/external-form/external-form.component.ts
  src/app/dtos/external-transaction-request-dto.ts
  src/app/services/bank-service/transaction.service.ts
Labels: size/L

#123 Home Page Components
  src/app/components/bank-exchange/bank-exchange.component.ts
  src/app/components/home/home.component.css
  src/app/components/home/home.component.html
  src/app/components/home/home.component.ts
  src/environments/environment.development.ts
Labels: size/L

#124 Forms Refactor
  src/app/components/companies/dialogs/add-company-dialog/add-company-dialog.component.html
  src/app/components/companies/dialogs/add-company-dialog/add-company-dialog.component.ts
  src/app/components/create-bank-profile/create-bank-profile.component.html
  src/app/components/users/dialogs/add-agent-dialog/add-agent-dialog.component.html
  src/app/components/users/dialogs/add-agent-dialog/add-agent-dialog.component.ts
  src/app/components/users/dialogs/add-employee-dialog/add-employee-dialog.component.html
  src/app/components/users/dialogs/add-employee-dialog/add-employee-dialog.component.ts
Labels: size/L

#125 Navbar and Accounts Guard
  src/app/app-routing.module.ts
  src/app/components/navigation-menu/navigation-menu.component.html
  src/app/components/navigation-menu/navigation-menu.component.ts
  src/app/guards/account.guard.spec.ts
  src/app/guards/account.guard.ts
  src/app/services/bank-service/account.service.ts
Labels: size/M

#126 Tab scroll fix
  src/app/components/create-bank-account/create-bank-account.component.css
  src/app/components/create-bank-account/create-bank-account.component.html
  src/app/components/transactions/transactions/transactions.component.css
  src/app/components/transactions/transactions/transactions.component.html
Labels: size/S

#127 Hide Accounts User Profile And CSS fixes
  src/app/components/cards/cards.component.css
  src/app/components/cards/cards.component.html
  src/app/components/create-bank-account/create-bank-account.component.css
  src/app/components/create-bank-account/create-bank-account.component.html
  src/app/components/transactions/transactions/transactions.component.css
  src/app/components/transactions/transactions/transactions.component.html
  src/app/components/user-profile/user-profile.component.html
Labels: size/M

#131 Create OWNERS
  OWNERS
Labels: size/XS

#130 Create OWNERS
  OWNERS
Labels: size/XS

#135 fontend yamal
  .prow/frontend.yaml
Labels: size/S, lgtm, approved

#136 Popravka stock-filter-component.css
  src/app/components/stocks/dialogs/stock-filter/stock-filter.component.css
Labels: size/XS, lgtm, approved
